spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smart_tool_cabinets}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    root: INFO
    smarttoolcabinets: DEBUG

